version: '2.2'

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}"
    container_name: elasticsearch
    ports:
      - ${ES_PORT}:9200
    volumes:
      - ${WORKING_DIR}/elasticsearch/data/:/usr/share/elasticsearch/data/:rw
      - ./conf/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
      - xpack.license.self_generated.type=${LICENSE}
    mem_limit: ${ELASTIC_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'You Know, for Search'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: "docker.elastic.co/kibana/kibana:${STACK_VERSION}"
    container_name: kibana
    volumes:
    - ${WORKING_DIR}/kibana/data:/usr/share/kibana/data:rw
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    mem_limit: ${KIBANA_MEM_LIMIT}
    ports:
      - ${KIBANA_PORT}:5601
    healthcheck:
          test: [
              "CMD-SHELL",
              "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
            ]
          interval: 10s
          timeout: 10s
          retries: 120
  logstash:
    image: "docker.elastic.co/logstash/logstash:${STACK_VERSION}"
    container_name: logstash
    volumes:
      - ./conf/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./conf/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./conf/logstash/filters/:/usr/share/logstash/filters/:ro
    command: sh -c "bin/logstash-plugin install logstash-filter-alter && logstash"
    # network_mode: "host"
  filebeat:
    image: "docker.elastic.co/beats/filebeat:${STACK_VERSION}"
    container_name: filebeat
    volumes:
      - ./conf/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./conf/filebeat/projets.csv:/var/log/projets.csv:ro
      # - ${PROJETS_CSV_PATH}:/var/log/projets.csv:ro
    # network_mode: "host"
networks:
  elk:
